apiVersion: v1
kind: Service
metadata:
  name: argocd-kube-svc
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 80
  selector:
    run: argocd-kube
  type: LoadBalancer
  externalIPs:
  - 192.168.0.22
